### ISSUE TITLE
Possibly more detail?

### ISSUE THREAD

**Issue by navett52** [samhogan/Minecraft-Unity3D#1]
https://github.com/samhogan/Minecraft-Unity3D/blob/c999f3e1b2b4b2c987c6353e63b4405683043dbc/Assets/Scripts/TerrainGenerator.cs#L266

Above should be the line of code in question. First off, I'm very thankful you made this and threw it up here. I'm basically using your code here as a reference to create a minecraft-like world but in Godot instead of Unity. This means that sometimes I run into issues where there isn't a direct 1 to 1 translation of something you did and this is one of those specific spots. I think I have a vague idea of what's going on here, but if you would be willing to give me some more detail on exactly why this is the way this is, I would be very grateful.

**Comment by samhogan** [comment]
Hi Evan, that's just a good ol' unity coroutine: https://docs.unity3d.com/Manual/Coroutines.html

That method will space out building chunks .2 seconds apart instead of just generating them all at once (for performance). With the coroutine, instead of the function running to completion, it will pause execution and resume every .2 seconds. The coroutine is started in line 203 when some new chunks need to be generated. I guess the IEnumerator return makes the method act sorta like a generator, idk, that's just how you write coroutines in unity. If you have more questions you can jump in my discord: https://discord.gg/NgM9zAA

And btw how did you find this repo, because I think you're in one of my classes at NKU
